### ISSUE TITLE
Cron funktioniert leider nicht auf Synology NAS

### ISSUE THREAD

**Issue by m-O-rpheus** [DeBaschdi/docker.easyepg#2]
Hallo,

vielen Dank für das Großartige Projekt.

Leider funktioniert der Cron bei mir am Synology NAS nicht.
Ich habe die Einrichtung über die EasyEPG Console erfolgreich abgeschlossen. Es wird auch die XML Datei mit den EPG Daten erzeugt. Rufe ich die EasyEPG Console neu auf, wird ebenfalls die XML neu generiert. Dies dauert immer zwischen 15 und 30 Minuten.

Leider wird der Cron bei mir nie ausgeführt. Egal welche Einstellungen ich vornehme.

Hier ein Screenshot meiner Synology Docker Einstellungen.

Viele Grüße
m0rph3u

![FireShot Capture 097 - MARKUS-NAS - Synology DiskStation - beowulf123456 synology me](https://user-images.githubusercontent.com/73857179/122516282-dc5af480-d00e-11eb-80e3-dd855e5a5508.png)

**Comment by flobiwankenobi** [comment]
Ich kann mich dem nur anschließen. Habe auch ein Synology NAS und der cron läuft nicht. Hast du eine Lösung gefunden?
